Models/Computer.cs
namespace LabManagerMvc.Models;

public class Computer
{
    public int Id { get; set; }
    public string Ram { get; set; }
    public string Processor { get; set; }

    public Computer() {}

    public Computer(int id, string ram, string processor)
    {
        Id = id;
        Ram = ram;
        Processor = processor;
    }
}

Models/ErrorViewModel.cs
namespace LabManagerMvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Lab.cs
namespace LabManagerMvc.Models;

public class Lab 
{
    public int Id { get; set; } 
    public int _Number { get; set; } 
    public string _Name { get; set; }
    public string _Block { get; set; }


    public Lab(int id, int _number, string _name, string _block)
    {
        Id = id;
        _Number = _number;
        _Name = _name;
        _Block = _block;
    }

    public Lab(){ }
}

Models/LabManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace LabManagerMvc.Models;

public class LabManagerContext : DbContext
{
    public DbSet<Computer> Computers { get; set; }
    public DbSet<Lab> Labs { get; set; }


    public LabManagerContext(DbContextOptions<LabManagerContext> options) : base(options)
    {}
}

Controllers/ComputerController.cs
using Microsoft.AspNetCore.Mvc;
using LabManagerMvc.Models;

namespace LabManagerMvc.Controllers;

public class ComputerController : Controller
{
    private readonly LabManagerContext _context;

    public ComputerController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Computers);
    }

    public IActionResult Show(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }
    public IActionResult Edit(int id){
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }
    public IActionResult Update([FromForm] Computer computer){
        if (!ModelState.IsValid)
        {
            return View(computer);
        }

    Computer? computerFound = _context.Computers.Find(computer.Id);

        if(computerFound == null)
        {
            return NotFound();
        }
        
        computerFound.Id = computer.Id;
        computerFound.Processor = computer.Processor;
        computerFound.Ram = computer.Ram;

        _context.Computers.Update(computerFound);
        _context.SaveChanges();
        return RedirectToAction("Index");

    }
    public IActionResult Create(){
        return View();
    }

    [HttpPost]
    public IActionResult Save([FromForm] Computer computer)
    {
        if (!ModelState.IsValid)
        {
            return View(computer);

        }

        _context.Computers.Add(computer);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }


    public IActionResult Delete(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }
         _context.Computers.Remove(computer);
        _context.SaveChanges();

        return View();
        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LabManagerMvc.Models;

namespace LabManagerMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LabController.cs
using Microsoft.AspNetCore.Mvc;
using LabManagerMvc.Models;

namespace LabManagerMvc.Controllers;

public class LabController : Controller
{
    private readonly LabManagerContext _context;

    public LabController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Labs);
    }

    public IActionResult Show(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }
    public IActionResult Edit(int id){
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }
    public IActionResult Update([FromForm] Lab lab){
        if (!ModelState.IsValid)
        {
            return View(lab);
        }

        Lab? labFound = _context.Labs.Find(lab.Id);

        if(labFound == null)
        {
            return NotFound();
        }
        
        labFound.Id = lab.Id;
        labFound._Name = lab._Name;
        labFound._Number = lab._Number;
        labFound._Block = lab._Block;

        _context.Labs.Update(labFound);
        _context.SaveChanges();
        return RedirectToAction("Index");

    }
    public IActionResult Create(){
        return View();
    }

    [HttpPost]
    public IActionResult Save([FromForm] Lab lab)
    {
        _context.Labs.Add(lab);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }


    public IActionResult Delete(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }
         _context.Labs.Remove(lab);
        _context.SaveChanges();

        return View();
        
    }
}

Views/Computer/Create.cshtml
@model LabManagerMvc.Models.Computer

@{
    ViewData["Title"] = "Cadastrar computador";
}

<h1>@ViewData["Title"]</h1>

<div>
    <!--<form action="CadastrarComputer" method="post">
        <label for="id">Id: </label>
            <input type="number" name="id" id="id" class="form-control" min="1" required>

        <label for="ram">Ram: </label>
        <input type="text" name="ram" id="ram" class="form-control" required>

        <label for="processor">Processador: </label>
        <input type="text" name="processor" id="processor" class="form-control" required>

        <button type="submit">Enviar</button>
    </form>-->
    
    <form asp-controller="Computer" asp-action="Save" method="post">
        <label for="id">Id: </label>
            <input type="number" name="id" id="id" class="form-control" min="1" required>

        <label for="ram">Ram: </label>
        <input type="text" name="ram" id="ram" class="form-control" required>

        <label for="processor">Processador: </label>
        <input type="text" name="processor" id="processor" class="form-control" required>

        <br/><button type="submit">Salvar</button>
    </form>
    
</div>

Views/Computer/Delete.cshtml
@{
    ViewData["Title"] = "Página de exclusão";
}

<div class="text-center">
    <h1 class="display-4">Computador excluído com sucesso</h1>
</div>

Views/Computer/Edit.cshtml
@model LabManagerMvc.Models.Computer

@{
    ViewData["Title"] = $"Computador {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<div>

<form asp-controller="Computer" asp-action="Update" method="post">
    
    <input type="hidden" asp-for="@Model.Id">

    <label for="Ram">Ram</label> <br/>
    <input asp-for="@Model.Ram" value="@Model.Ram"> <br/>
     <!--<span asp-validation-for="Ram" class="text-danger"></span> <br/>-->

    <label for="Processor">Processor</label> <br/>
    <input asp-for="@Model.Processor" value="@Model.Processor"> <br/>
    <!--<span asp-validation-for="Processor" class="text-danger"></span><br/>-->

    <button class="btn btn-primary btn-sm" type="submit">Enviar</button>

</form>

</div>

Views/Computer/Index.cshtml
@model IEnumerable<LabManagerMvc.Models.Computer>

@{
    ViewData["Title"] = "Computadores";
}
<h1>@ViewData["Title"]</h1><br/>


<a asp-controller="Computer" asp-action="Create">
    Cadastrar Computador
</a><br/><br/>

@if(Model.Count() == 0)
{
    <p>Nenhum computador cadastrado</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ram</th>
                <th>Processador</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var computer in Model)
            {
                <tr>
                    <td>@computer.Id</td>
                    <td>@computer.Ram</td>
                    <td>@computer.Processor</td>
                    <td>
                        
                        <a asp-controller="Computer" asp-action="Show" asp-route-id="@computer.Id">
                            Ver detalhes
                         </a><br/><br/>

                         <a asp-controller="Computer" asp-action="Edit" asp-route-id="@computer.Id">
                            Editar
                         </a><br/><br/>
                        
                        <a asp-controller="Computer" asp-action="Delete" asp-route-id="@computer.Id">
                            Deletar
                         </a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Computer/Show.cshtml
@model LabManagerMvc.Models.Computer

@{
    ViewData["Title"] = $"Computador {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<p>
    <b>Id:</b> @Model.Id
</p>
<p>
    <b>Ram:</b> @Model.Ram
</p>
<p>
    <b>Processor:</b> @Model.Processor
</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Lab/Create.cshtml
@model LabManagerMvc.Models.Lab

@{
    ViewData["Title"] = "Cadastrar laboratório";
}

<h1>@ViewData["Title"]</h1>

<div>
    
    <form asp-controller="Lab" asp-action="Save" method="post">
        <label for="id">Id: </label>
            <input type="number" name="id" id="id" class="form-control" min="1" required>

        <label for="_name">Name: </label>
        <input type="text" name="_name" id="_name" class="form-control" required>

        <label for="_number">Number: </label>
        <input type="number" name="_number" id="_number" class="form-control" min="1" required>

        <label for="_block">Block: </label>
        <input type="text" name="_block" id="_block" class="form-control" required>

        <br/><button type="submit">Salvar</button>
    </form>

</div>

Views/Lab/Delete.cshtml
@{
    ViewData["Title"] = "Página de exclusão";
}

<div class="text-center">
    <h1 class="display-4">Laboratório excluído com sucesso</h1>
</div>

Views/Lab/Edit.cshtml
@model LabManagerMvc.Models.Lab

@{
    ViewData["Title"] = $"Laboratório {Model._Name}";
}
<h1>@ViewData["Title"]</h1>

<div>

<form asp-controller="Lab" asp-action="Update" method="post">
    
    <input type="hidden" asp-for="@Model.Id">

    <label for="_Name">Name</label> <br/>
    <input asp-for="@Model._Name" value="@Model._Name"  class="form-control">
     <!--<span asp-validation-for="_Name" class="text-danger"></span>-->

     <label for="_number">Number</label>
        <input asp-for="@Model._Number" value="@Model._Number" class="form-control" min="1" required>
        <!--<span asp-validation-for="_Number" class="text-danger"></span>-->

    <label for="_Block">Block</label> <br/>
    <input asp-for="@Model._Block" value="@Model._Block"  class="form-control"> <br/>
    <!--<span asp-validation-for="_Block" class="text-danger"></span><br/>-->

    <button class="btn btn-primary btn-sm" type="submit">Enviar</button>

</form>

</div>

Views/Lab/Index.cshtml
@model IEnumerable<LabManagerMvc.Models.Lab>

@{
    ViewData["Title"] = "Laboratórios";
}
<h1>@ViewData["Title"]</h1><br/>

<a asp-controller="Lab" asp-action="Create">
    Cadastrar Laboratório
</a><br/><br/>

@if(Model.Count() == 0)
{
    <p>Nenhum laboratório cadastrado</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Number</th>
                <th>Block</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var lab in Model)
            {
                <tr>
                    <td>@lab.Id</td>
                    <td>@lab._Name</td>
                    <td>@lab._Number</td>
                    <td>@lab._Block</td>
                    <td>
                        
                        <a asp-controller="Lab" asp-action="Show" asp-route-id="@lab.Id">
                            Ver detalhes
                         </a><br/><br/>

                         <a asp-controller="Lab" asp-action="Edit" asp-route-id="@lab.Id">
                            Editar
                         </a><br/><br/>
                        
                        <a asp-controller="Lab" asp-action="Delete" asp-route-id="@lab.Id">
                            Deletar
                         </a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Lab/Show.cshtml
@model LabManagerMvc.Models.Lab

@{
    ViewData["Title"] = $"Laboratório {Model._Name}";
}
<h1>@ViewData["Title"]</h1>

<p>
    <b>Id:</b> @Model.Id
</p>
<p>
    <b>Name:</b> @Model._Name
</p>
<p>
    <b>Number:</b> @Model._Number
</p>
<p>
    <b>Block:</b> @Model._Block
</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabManagerMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LabManagerMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabManagerMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Index">Computador</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lab" asp-action="Index">Lab</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LabManagerMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>